### ISSUE TITLE
$ref that points to github?

### ISSUE THREAD

**Issue by epugh** [marksparkza/jschon.dev#2]
I have this cut down schema:

```
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "http://github.com/o19s/ubi/schema/event.request.schema.json",
  "title": "Event",
  "description": "An event that occurred, typically in response to a user.  See https://github.com/o19s/opensearch-ubi/blob/2.14.0/documentation/schemas.md abd https://github.com/o19s/opensearch-ubi/blob/2.14.0/src/main/resources/events-mapping.json for more info.",
  "type": "object",
  "required": ["query_id"],
  "properties": {
    "application": {
      "description": "name of the application tracking UBI events (e.g. _amazon-shop_, _ABC-microservice_)",
      "type": "string"
    },
    "query_id": {
      "$ref": "https://raw.githubusercontent.com/o19s/ubi/main/schema/query_id.schema.json#/definitions/query_id"
    }
  }
}
```

And I get an error:

```
{
    "exception": "CatalogError",
    "message": "A source is not available for \"https://raw.githubusercontent.com/o19s/ubi/main/schema/query_id.schema.json\""
}
```

is this due to limitions in the platform?  do most people not use the $ref with a url?

**Comment by marksparkza** [comment]
The jschon.dev website does not support remote references. For remote use cases, the jschon library does support remote references against base URLs (sources) that have been registered with the [add_uri_source](https://github.com/marksparkza/jschon/blob/60c87b31425a64bac7d21cb2bbaacc071538ed5c/jschon/catalog/__init__.py#L102) method on a `Catalog` instance. Requiring remote sources to be registered prevents loading from arbitrary remote locations, which is a security risk if schema content is untrusted.
